var require = meteorInstall({"folder":{"funcs.ls.js":function(require){

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                     //
// folder/funcs.ls.js                                                                                  //
//                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                       //
// Generated by LiveScript 1.5.0
this._ = lodash;
if (Meteor.isClient) {
  this.m = require('mithril');
  this.state = {};
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////

}},"both.ls.js":function(){

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                     //
// both.ls.js                                                                                          //
//                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                       //
// Generated by LiveScript 1.5.0
this.coll = {};
coll.bangsal = new Meteor.Collection('bangsal');
coll.marquee = new Meteor.Collection('marquee');
coll.marquee.allow({
  insert: function(){
    return true;
  }
});
/////////////////////////////////////////////////////////////////////////////////////////////////////////

},"client.ls.js":function(){

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                     //
// client.ls.js                                                                                        //
//                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                       //
// Generated by LiveScript 1.5.0
var makeRooms, front;
if (Meteor.isClient) {
  makeRooms = function(obj){
    var attr;
    attr = {
      room: function(doc, groupId){
        return {
          style: {
            border: '1px solid white'
          },
          'class': function(){
            var size;
            size = Math.round(12 / obj.rooms.length);
            if (size === 1) {
              size += 2;
            }
            return "m" + size + " " + obj.color;
          }(),
          ondblclick: function(){
            state.edit = {
              group: groupId,
              room: doc
            };
            return m.redraw();
          }
        };
      }
    };
    return m('.row', m('.divider'), m('h4.center', attr.header, obj.label), obj.rooms.map(function(i){
      return m('.col', attr.room(i, obj.name), m('.col.m6', m('p.white-text.center', _.startCase(i.name))), m('.col.m6', m('p.white-text.center', (i.use || 0) + " of " + i.cap)));
    }));
  };
  front = function(){
    var attr;
    attr = {
      form: {
        bangsal: {
          onsubmit: function(e){
            e.preventDefault();
            Meteor.call('update', state.edit, e.target[0].value);
            state.edit = null;
            return $('#modalBangsal').modal('close');
          }
        },
        marquee: {
          onsubmit: function(e){
            e.preventDefault();
            return Meteor.call('marquee', {
              text: e.target[0].value
            }, function(err, res){
              if (res) {
                return $('#modalMarquee').modal('close');
              }
            });
          }
        }
      },
      reset: {
        ondblclick: function(){
          return Meteor.call('reset', function(err, res){
            if (res) {
              return m.redraw();
            }
          });
        }
      },
      modal: {
        bangsal: {
          oncreate: function(){
            return $('#modalBangsal').modal().modal('open');
          }
        }
      },
      marquee: {
        oncreate: function(){
          return $('.marquee').marquee({
            duration: 15000
          });
        },
        ondblclick: function(){
          return $('#modalMarquee').modal().modal('open');
        }
      }
    };
    return {
      view: function(){
        var ref$;
        return m('.container', m('.row', m('.left', m('h5', moment(new Date()).format('D MMM YYYY'))), m('.right', m('a', attr.reset, 'Reset'))), state.edit ? m('.modal#modalBangsal', attr.modal.bangsal, m('form', attr.form.bangsal, m('.modal-content', m('h4', 'Bangsal terpakai'), m('.input-field', m('input', {
          type: 'text',
          id: state.edit.group
        }))), m('.modal-footer', m('input.btn-flat', {
          type: 'submit'
        })))) : void 8, coll.bangsal.find().fetch().map(makeRooms), m('.marquee', attr.marquee, m('h5', ((ref$ = coll.marquee.findOne()) != null ? ref$.text : void 8) || 'no info')), m('.modal#modalMarquee', m('form', attr.form.marquee, m('.modal-content', m('h4', 'Konten Marquee'), m('.input-field', m('input', {
          type: 'text',
          id: 'marquee'
        }))), m('.modal-footer', m('input.btn-flat', {
          type: 'submit'
        })))));
      }
    };
  };
  Meteor.subscribe('coll', {
    onReady: function(){
      return m.mount(document.body, front());
    }
  });
  coll.bangsal.find().observe({
    changed: function(){
      return m.redraw();
    }
  });
  coll.marquee.find().observe({
    added: function(){
      return m.redraw();
    }
  });
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////

},"seeder.ls.js":function(){

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                     //
// seeder.ls.js                                                                                        //
//                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                       //
// Generated by LiveScript 1.5.0
if (Meteor.isServer) {
  this.seeder = [
    {
      name: 'hnd',
      label: 'Hang Nadim',
      color: 'red',
      rooms: [
        {
          name: 'laki-laki',
          cap: 6
        }, {
          name: 'perempuan',
          cap: 7
        }
      ]
    }, {
      name: 'hlk',
      label: 'Hang Lekir',
      color: 'blue',
      rooms: [
        {
          name: 'laki-laki',
          cap: 6
        }, {
          name: 'perempuan',
          cap: 6
        }, {
          name: 'anak',
          cap: 10
        }
      ]
    }, {
      name: 'dmd',
      label: 'Dang Merdu',
      color: 'green',
      rooms: [
        {
          name: 'dm2',
          cap: 2
        }, {
          name: 'dm3',
          cap: 2
        }, {
          name: 'dm4',
          cap: 4
        }, {
          name: 'dm5',
          cap: 3
        }, {
          name: 'dm6',
          cap: 3
        }, {
          name: 'dm8',
          cap: 2
        }, {
          name: 'dm9',
          cap: 2
        }, {
          name: 'dm10',
          cap: 1
        }, {
          name: 'dm11',
          cap: 2
        }, {
          name: 'dm13',
          cap: 1
        }, {
          name: 'dm13',
          cap: 3
        }, {
          name: 'dm14',
          cap: 3
        }, {
          name: 'isolasi',
          cap: 1
        }
      ]
    }, {
      name: 'others',
      label: 'Lainnya',
      color: 'purple',
      rooms: [
        {
          name: 'perina',
          cap: 3
        }, {
          name: 'icu',
          cap: 2
        }, {
          name: 'kb',
          cap: 18
        }
      ]
    }
  ];
  if (!coll.bangsal.findOne()) {
    seeder.map(function(it){
      return coll.bangsal.insert(it);
    });
  }
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////

},"server.ls.js":function(){

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                     //
// server.ls.js                                                                                        //
//                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                       //
// Generated by LiveScript 1.5.0
if (Meteor.isServer) {
  Meteor.publish('coll', function(){
    return [coll.bangsal.find({}), coll.marquee.find({})];
  });
  Meteor.methods({
    update: function(obj, num){
      var find, sel, mod;
      find = coll.bangsal.findOne({
        name: obj.group
      });
      sel = {
        _id: find._id
      };
      mod = {
        $set: {
          rooms: function(){
            var index;
            index = _.findIndex(find.rooms, function(it){
              return it.name === obj.room.name;
            });
            find.rooms[index].use = parseInt(num);
            return find.rooms;
          }()
        }
      };
      return coll.bangsal.update(sel, mod);
    },
    reset: function(){
      coll.bangsal.remove({});
      coll.marquee.remove({});
      return seeder.map(function(it){
        return coll.bangsal.insert(it);
      });
    },
    marquee: function(obj){
      coll.marquee.remove({});
      return coll.marquee.insert({
        text: obj.text
      });
    }
  });
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////

}},{
  "extensions": [
    ".js",
    ".json"
  ]
});
require("/folder/funcs.ls.js");
require("/both.ls.js");
require("/client.ls.js");
require("/seeder.ls.js");
require("/server.ls.js");