var require = meteorInstall({"folder":{"funcs.ls.js":function(require){

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                     //
// folder/funcs.ls.js                                                                                  //
//                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                       //
// Generated by LiveScript 1.5.0
this._ = lodash;
if (Meteor.isClient) {
  this.m = require('mithril');
  this.state = {};
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////

}},"both.ls.js":function(){

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                     //
// both.ls.js                                                                                          //
//                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                       //
// Generated by LiveScript 1.5.0
this.coll = {};
coll.bangsal = new Meteor.Collection('bangsal');
coll.marquee = new Meteor.Collection('marquee');
coll.marquee.allow({
  insert: function(){
    return true;
  }
});
coll.lastUpdate = new Meteor.Collection('lastUpdate');
coll.lastUpdate.allow({
  insert: function(){
    return true;
  }
});
/////////////////////////////////////////////////////////////////////////////////////////////////////////

},"client.ls.js":function(){

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                     //
// client.ls.js                                                                                        //
//                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                       //
// Generated by LiveScript 1.5.0
var makeRooms, front;
if (Meteor.isClient) {
  makeRooms = function(obj){
    var attr;
    attr = {
      room: function(doc, groupId){
        return {
          style: {
            border: '1px solid white'
          },
          'class': function(){
            var size;
            size = Math.round(12 / obj.rooms.length);
            if (size === 1) {
              size += 2;
            }
            return "m" + size + " " + obj.color;
          }(),
          ondblclick: function(){
            if (Meteor.userId()) {
              state.edit = {
                group: groupId,
                room: doc
              };
              return m.redraw();
            }
          }
        };
      }
    };
    return m('.row', m('.divider'), m('h4.center', attr.header, obj.label), obj.rooms.map(function(i){
      return m('.col', attr.room(i, obj.name), m('.col.m6', m('p.white-text.center', i.name)), m('.col.m6', m('p.white-text.center', (i.use || 0) + " of " + i.cap)));
    }));
  };
  front = function(){
    var attr;
    attr = {
      form: {
        bangsal: {
          onsubmit: function(e){
            e.preventDefault();
            Meteor.call('update', state.edit, e.target[0].value);
            Meteor.call('lastUpdate');
            state.edit = null;
            return $('#modalBangsal').modal('close');
          }
        },
        marquee: {
          onsubmit: function(e){
            e.preventDefault();
            return Meteor.call('marquee', {
              text: e.target[0].value
            }, function(err, res){
              if (res) {
                return $('#modalMarquee').modal('close');
              }
            });
          }
        },
        login: {
          onsubmit: function(e){
            var ref$, username, password;
            e.preventDefault();
            ref$ = _.map(e.target), username = ref$[0], password = ref$[1];
            return Meteor.loginWithPassword(username.value, password.value, function(err){
              return $('#modalLogin').modal('close');
            });
          }
        }
      },
      reset: {
        ondblclick: function(){
          if (Meteor.userId()) {
            return Meteor.call('reset', function(err, res){
              if (res) {
                return m.redraw();
              }
            });
          }
        }
      },
      modal: {
        bangsal: {
          oncreate: function(){
            return $('#modalBangsal').modal().modal('open');
          }
        },
        login: {
          oncreate: function(){
            return $('#modalLogin').modal();
          },
          onclick: function(){
            return $('#modalLogin').modal('open');
          }
        }
      },
      marquee: {
        oncreate: function(){
          return $('.marquee').marquee({
            duration: 15000
          });
        },
        ondblclick: function(){
          return Meteor.userId() && $('#modalMarquee').modal().modal('open');
        }
      }
    };
    return {
      view: function(){
        var date, ref$, ref1$;
        return m('div', m('nav.teal', m('.nav-wrapper', m('a.brand-logo.center', 'Sistem Informasi Ketersediaan Bangsal RSUD Petala Bumi'))), m('.container', m('.row', (date = (ref$ = coll.lastUpdate.findOne()) != null ? ref$.date : void 8) ? m('h5.left', moment(date).format('LT D MM YYYY')) : void 8, m('a.right', attr.modal.login, 'Login'), m('a.right', attr.reset, 'Reset')), state.edit ? m('.modal#modalBangsal', attr.modal.bangsal, m('form', attr.form.bangsal, m('.modal-content', m('h4', 'Bangsal terpakai'), m('.input-field', m('input', {
          type: 'text',
          id: state.edit.group
        }))), m('.modal-footer', m('input.btn-flat', {
          type: 'submit'
        })))) : void 8, m('.modal#modalLogin', m('.modal-content', m('form', attr.form.login, m('h5.center', 'Login Admin Bangsal'), m('input', {
          type: 'text',
          id: 'username',
          placeholder: 'Username'
        }), m('input', {
          type: 'password',
          id: 'password',
          placeholder: 'Password'
        }), m('input.btn', {
          type: 'submit',
          value: 'Login'
        })))), coll.bangsal.find().fetch().map(makeRooms), m('.marquee', attr.marquee, m('h5', ((ref1$ = coll.marquee.findOne()) != null ? ref1$.text : void 8) || 'no info')), m('.modal#modalMarquee', m('form', attr.form.marquee, m('.modal-content', m('h4', 'Konten Marquee'), m('.input-field', m('input', {
          type: 'text',
          id: 'marquee'
        }))), m('.modal-footer', m('input.btn-flat', {
          type: 'submit'
        }))))));
      }
    };
  };
  Meteor.subscribe('coll', {
    onReady: function(){
      return m.mount(document.body, front());
    }
  });
  coll.bangsal.find().observe({
    changed: function(){
      return m.redraw();
    }
  });
  coll.marquee.find().observe({
    added: function(){
      return m.redraw();
    }
  });
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////

},"seeder.ls.js":function(){

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                     //
// seeder.ls.js                                                                                        //
//                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                       //
// Generated by LiveScript 1.5.0
if (Meteor.isServer) {
  this.seeder = [
    {
      name: 'hnd',
      label: 'Ruangan Hang Nadim',
      color: 'red',
      rooms: [
        {
          name: 'Laki-laki',
          cap: 6
        }, {
          name: 'Perempuan',
          cap: 7
        }
      ]
    }, {
      name: 'hlk',
      label: 'Ruangan Hang Lekir',
      color: 'blue',
      rooms: [
        {
          name: 'Laki-laki',
          cap: 6
        }, {
          name: 'Perempuan',
          cap: 6
        }, {
          name: 'Anak',
          cap: 10
        }
      ]
    }, {
      name: 'dmd',
      label: 'Ruangan Dang Merdu',
      color: 'green',
      rooms: [
        {
          name: 'DM2',
          cap: 2
        }, {
          name: 'DM3',
          cap: 2
        }, {
          name: 'DM4',
          cap: 4
        }, {
          name: 'DM5',
          cap: 3
        }, {
          name: 'DM6',
          cap: 3
        }, {
          name: 'DM8',
          cap: 2
        }, {
          name: 'DM9',
          cap: 2
        }, {
          name: 'DM10',
          cap: 1
        }, {
          name: 'DM11',
          cap: 2
        }, {
          name: 'DM12',
          cap: 1
        }, {
          name: 'DM13',
          cap: 3
        }, {
          name: 'DM14',
          cap: 3
        }, {
          name: 'Isolasi',
          cap: 1
        }
      ]
    }, {
      name: 'others',
      label: 'Ruangan Lainnya',
      color: 'purple',
      rooms: [
        {
          name: 'Perina',
          cap: 3
        }, {
          name: 'ICU',
          cap: 2
        }, {
          name: 'Dang Purnama',
          cap: 18
        }
      ]
    }
  ];
  if (!coll.bangsal.findOne()) {
    seeder.map(function(it){
      return coll.bangsal.insert(it);
    });
  }
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////

},"server.ls.js":function(){

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                     //
// server.ls.js                                                                                        //
//                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                       //
// Generated by LiveScript 1.5.0
if (Meteor.isServer) {
  Meteor.publish('coll', function(){
    return [coll.bangsal.find({}), coll.marquee.find({}), coll.lastUpdate.find({})];
  });
  Meteor.methods({
    update: function(obj, num){
      var find, sel, mod;
      find = coll.bangsal.findOne({
        name: obj.group
      });
      sel = {
        _id: find._id
      };
      mod = {
        $set: {
          rooms: function(){
            var index;
            index = _.findIndex(find.rooms, function(it){
              return it.name === obj.room.name;
            });
            find.rooms[index].use = parseInt(num);
            return find.rooms;
          }()
        }
      };
      return coll.bangsal.update(sel, mod);
    },
    reset: function(){
      coll.bangsal.remove({});
      coll.marquee.remove({});
      return seeder.map(function(it){
        return coll.bangsal.insert(it);
      });
    },
    marquee: function(obj){
      coll.marquee.remove({});
      return coll.marquee.insert({
        text: obj.text
      });
    },
    lastUpdate: function(){
      coll.lastUpdate.remove({});
      return coll.lastUpdate.insert({
        date: new Date()
      });
    }
  });
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////

}},{
  "extensions": [
    ".js",
    ".json"
  ]
});
require("/folder/funcs.ls.js");
require("/both.ls.js");
require("/client.ls.js");
require("/seeder.ls.js");
require("/server.ls.js");