var require = meteorInstall({"folder":{"funcs.ls.js":function(require){

//////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                      //
// folder/funcs.ls.js                                                                                   //
//                                                                                                      //
//////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                        //
// Generated by LiveScript 1.5.0
this._ = lodash;
if (Meteor.isClient) {
  this.m = require('mithril');
  this.state = {};
}
//////////////////////////////////////////////////////////////////////////////////////////////////////////

}},"both.ls.js":function(){

//////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                      //
// both.ls.js                                                                                           //
//                                                                                                      //
//////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                        //
// Generated by LiveScript 1.5.0
this.tabel = new Mongo.Collection('coll');
tabel.allow({
  insert: function(){
    return true;
  }
});
//////////////////////////////////////////////////////////////////////////////////////////////////////////

},"client.ls.js":function(){

//////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                      //
// client.ls.js                                                                                         //
//                                                                                                      //
//////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                        //
// Generated by LiveScript 1.5.0
var comp, slice$ = [].slice;
if (Meteor.isClient) {
  comp = {
    layout: function(content){
      return {
        view: function(){
          return m('div', m('.navbar-fixed', m('nav.green', m('.nav-wrapper', m('a.brand-logo.center', 'Konten Tabel'), m('ul.right', m('li', m('a', 'Login')))))), m('ul.fixed.side-nav', m('li.grey.lighten-2', m('a.center', m('b', 'Daftar Tabel'))), tabel.find().fetch().map(function(i){
            return m('li', m('a.center', {
              href: "/tabel/" + i.idtabel,
              oncreate: m.route.link
            }, m('b', i.title.substring(0, 27))));
          })), m('div', {
            style: "padding-left: 160px"
          }, m(content)));
        }
      };
    },
    unggah: function(){
      var fileInput;
      fileInput = function(arg$){
        var target;
        target = arg$.target;
        return Papa.parse(target.files[0], {
          complete: function(res){
            var reducer, reduced;
            reducer = function(acc, val){
              if (acc[val[0]]) {
                acc[val[0]].push(_.tail(val));
              } else {
                acc[val[0]] = [_.tail(val)];
              }
              return acc;
            };
            reduced = _.reduce(res.data, reducer, {});
            return _.map(reduced, function(arg$, idtabel){
              var ref$, title, header, rows;
              ref$ = arg$[0], title = ref$[0], header = arg$[1], rows = slice$.call(arg$, 2);
              if (idtabel) {
                return tabel.insert({
                  idtabel: idtabel,
                  title: title,
                  header: header,
                  rows: rows
                });
              }
            });
          }
        });
      };
      return {
        view: function(){
          return m('.container', m('br'), m('.btn', m('input', {
            type: 'file',
            name: 'Upload',
            onchange: fileInput
          })));
        }
      };
    },
    semua: function(){
      return {
        view: function(){
          return m('.container', tabel.find().fetch().map(function(i){
            return m('div', m('h5', i.title), m('table', m('tr', i.header.map(function(j){
              return m('th', j);
            })), i.rows.map(function(j){
              return m('tr', j.map(function(k){
                return m('td', k);
              }));
            })));
          }));
        }
      };
    },
    tabel: function(){
      return {
        view: function(){
          var found;
          found = tabel.findOne({
            idtabel: m.route.param('idtabel')
          });
          return m('.container', m('h4', found.title), m('table', m('tr', found.header.map(function(i){
            return m('th', i);
          })), found.rows.map(function(i){
            return m('tr', i.map(function(j){
              return m('td', j);
            }));
          })));
        }
      };
    }
  };
  Meteor.subscribe('tabel', {
    onReady: function(){
      return m.route(document.body, '/semua', {
        '/semua': comp.layout(comp.semua),
        '/unggah': comp.layout(comp.unggah),
        '/tabel/:idtabel': comp.layout(comp.tabel)
      });
    }
  });
}
//////////////////////////////////////////////////////////////////////////////////////////////////////////

},"server.ls.js":function(){

//////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                      //
// server.ls.js                                                                                         //
//                                                                                                      //
//////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                        //
// Generated by LiveScript 1.5.0
if (Meteor.isServer) {
  Meteor.publish('tabel', function(){
    return tabel.find({});
  });
  Meteor.methods({
    upsert: function(doc){
      return tabel.upsert(doc._id, doc);
    },
    remove: function(doc){
      return tabel.remove(doc._id);
    }
  });
}
//////////////////////////////////////////////////////////////////////////////////////////////////////////

}},{
  "extensions": [
    ".js",
    ".json"
  ]
});
require("/folder/funcs.ls.js");
require("/both.ls.js");
require("/client.ls.js");
require("/server.ls.js");